### ISSUE TITLE
The zone_create says it needs a valid domain

### ISSUE THREAD

**Issue by xokaido** [jamesryanbell/cloudflare#1]
Hello, I am very glad you've created such a great tool, I tried the script out but unfortunately the
zone class reports it needs a valid domain though the domain name was 100% valid, usable and registered. Can you please have a look at it fix the bug (if it's a bug)?...
Thanks for your attention.

**Comment by jamesryanbell** [comment]
Hi

Could please provide me with more details on the issue you are having please; sample code, error messages etc... would all be very useful in me being able to replicate this issue.

Thanks,
James
