### ISSUE TITLE
Typo in AccessRules

### ISSUE THREAD

**Issue by devicenull** [jamesryanbell/cloudflare#12]
https://github.com/jamesryanbell/cloudflare/blob/master/src/CloudFlare/User/Firewall/AccessRules.php#L18

'class AccesRules'

missing s

**Comment by devicenull** [comment]
Similarly, AccessRules should be in the Cloudflare\User\Firewall namespace, not Cloudflare\User

**Comment by jamesryanbell** [comment]
Thanks, all sorted in the latest commit, also fixed a few other namespace issues too.
