### ISSUE TITLE
Invalid request headers... Invalid Content-Type header

### ISSUE THREAD

**Issue by Lusitaniae** [jamesryanbell/cloudflare#15]
This happens when running the activation_check() from Cloudflare\Zone.

Full error log is:
```
array:5 [▼
  "error" => ""
  "http_code" => 400
  "method" => "put"
  "result" => "{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6105,"message":"Invalid Content-Type header, valid values are application\/json,multipart\/form-data"}]}],"messages":[],"result":null}"
  "information" => array:26 [▶]
]
```

There seems to be a few forks fixing this.

**Comment by jamesryanbell** [comment]
I've applied this fix in the latest update.

Thanks

**Comment by Lusitaniae** [comment]
Thanks for addressing both issues :)
I noticed now that I was loading v1 instead of following the dev-master branch!

I'm gonna continue looking at this for a while and help if possible.
