### ISSUE TITLE
Zone pause/unpause is making wrong request

### ISSUE THREAD

**Issue by Lusitaniae** [jamesryanbell/cloudflare#17]
https://api.cloudflare.com/#zone-edit-zone-properties

It should be a patch request and send paused as a boolean.

curl -X PATCH "https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353" \
--data '{"paused":true}'

**Comment by jamesryanbell** [comment]
Hi

It looks like the Edit Zone Properties method was updated by CloudFlare, they have combined pausing, editing vanity name servers and changing plans together. As the endpoint only allows you to do one at a time I have created individual methods for each one.

Long story short! this should be sorted now in the latest release.

Thanks,
James

**Comment by Lusitaniae** [comment]
I made a pull request regarding this, it needed a few small extra things!

Thanks,
Pedro
