### ISSUE TITLE
Enable Cloudflare when creating DNS zone

### ISSUE THREAD

**Issue by Lusitaniae** [jamesryanbell/cloudflare#19]
I'm trying to enable Cloudflare features when creating a new zone, by default its only DNS, it should be doable by adding proxied => true to the data array in the create function.

But the code, as is, doesn't work as the bool will be converted to something that Cloudflare doesn't accept.

Casting the parameters as an object seems to do it, but would require some changes.

```
  if($method === 'post') {
            if(preg_match("/\/dns_records/", $path))
              $data = (object) array (
                    'type'    => "A",
                    'name'    => "website.com",
                    'content' => "188.18.28.38",
        	    'proxied' => true,
                    'ttl'     => 120
                );
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
            $headers[] = "Content-type: application/json";
        } else if ($method === 'put') {
```

Any ideas what would be the best way to do it?

**Comment by jamesryanbell** [comment]
Hi

Thanks for this, I have made some changes in the latest version which means that all of the requests use json data. Using json means that the properties type and values are maintained.

Thanks,
James
