### ISSUE TITLE
var_dump in post request

### ISSUE THREAD

**Issue by snellingio** [jamesryanbell/cloudflare#21]
Library currently var_dumps on post request, which looks like a debug statement.

https://github.com/jamesryanbell/cloudflare/blob/master/src/CloudFlare/Api.php#L232

Will make a PR later.

**Comment by jamesryanbell** [comment]
Apologies! I will sort this in a few minutes.

**Comment by jamesryanbell** [comment]
This is now fixed in the latest version.

My embarrassment will take to fix!

**Comment by snellingio** [comment]
No worries! You got to it before me!
