### ISSUE TITLE
More Predictable Versioning

### ISSUE THREAD

**Issue by aaronhuisinga** [jamesryanbell/cloudflare#22]
Is there any chance we could get a more predictable versioning system for this package? I see you tagged a v1 release back in 2015, but since that release is out of date any of us that want to stay up to date are forced to use the dev-master tag through Composer, which is never a good practice. Would it be possible to have new releases follow a versioning system so that we can define a set version for Packagist and make sure that we don't end up pulling breaking changes in the future?

Thanks!

**Comment by jamesryanbell** [comment]
Hi

Yes this is something that's on my radar, should have some time this weekend to do a few bits on this project so this will be factored in.

Thanks,
James

**Comment by aaronhuisinga** [comment]
Looks great now. Thanks James!
