### ISSUE TITLE
Unable to create MX records

### ISSUE THREAD

**Issue by EdBailey** [jamesryanbell/cloudflare#23]
I'm receiving the following error when trying to create MX records using `CloudFlare/Zone/Dns->create()`:
```
object(stdClass)[17]
      public 'code' => int 1004
      public 'message' => string 'DNS Validation Error' (length=20)
      public 'error_chain' => 
        array (size=1)
          0 => 
            object(stdClass)[16]
              public 'code' => int 9008
              public 'message' => string 'Invalid priority, priority must be set and be between 0 and 65535' (length=65)
```

This appears to be because there is no parameter for setting a priority. Am I missing something here or does it just need to be added to the function?

Cheers

**Comment by jamesryanbell** [comment]
Hi

This should be fixed now in the latest version, unfortunately it wasn't mentioned in the Cloudflare API docs.

Thanks,
James
