### ISSUE TITLE
How I can create an SRV record?

### ISSUE THREAD

**Issue by xGabryMC** [jamesryanbell/cloudflare#24]
How I can create/edit/delete an SRV record?

**Comment by jamesryanbell** [comment]
Hi

A SRV record can be added/edited/deleted via the standard create DNS record methods, you just need to specify the type as 'SRV'.

Code example:
```
$client = new Cloudflare\Api('email@example.com', 'API_KEY');

// Create a new DNS record
$dns = new Cloudflare\Zone\Dns($client);
$dns->create('12345678901234567890', 'SRV', 'name.com', '127.0.0.1', 120);
```

Thanks,
James

**Comment by jamesryanbell** [comment]
I've merge you're pull request so this feature is now in the package, thanks again.
