### ISSUE TITLE
Generated link in readme.md seems incorrect

### ISSUE THREAD

**Issue by holtkamp** [jamesryanbell/cloudflare#25]
Just hover the link in the screenshot below. Tried to see what goes wrong, might be something in the way how GitHub parses Markdown

![screen shot 2016-06-22 at 12 37 32](https://cloud.githubusercontent.com/assets/776405/16263764/4d48416a-3876-11e6-9c61-07d2c7267a09.png)

**Comment by jamesryanbell** [comment]
Hi

Thanks, I've updated the readme

Thanks,
James
