### ISSUE TITLE
Incorrect type declaration of $configuration param

### ISSUE THREAD

**Issue by arturponiat** [jamesryanbell/cloudflare#31]
https://github.com/jamesryanbell/cloudflare/blame/master/src/CloudFlare/User/Firewall/AccessRules.php#L65

This method required `object $configuration` and causes an error.
Please remove `object` word or change type hint

**Comment by jamesryanbell** [comment]
Hi

I will try and sort this tonight, feel free to submit a PR though if you want to.

Thanks,
James

**Comment by jamesryanbell** [comment]
This is now fixed in the latest release, 1.6.11

Thanks,
James
