### ISSUE TITLE
API rate limiting

### ISSUE THREAD

**Issue by 2ge** [jamesryanbell/cloudflare#32]
Hi,

my server have been blocked from Cloudflare, because script overload API requests. It is possible to implement API rate limiting?

https://api.cloudflare.com/#requests

"Rate limiting
The CloudFlare API sets a maximum of 1,200 requests in a five minute period.
Cache-Tag purging has a lower rate limit of up to 2,000 purge API calls in every 24 hour period. You may purge up to 30 tags in one API call."

**Comment by Sm0ke0ut** [comment]
I'm not sure if this should be part of this package. The package only provide access to the Cloudflare API and can not decide what should happen when such limit is reached.
The action which needs to be taken as soon such limit is reached is depending on the application/implementation itself.

However... This package is performing an extra API call on every request to check if the authenticated user is having the right permissions, which leads to an increased amount of API requests. I've made a PR to remove this premature check in https://github.com/jamesryanbell/cloudflare/pull/33

**Comment by jamesryanbell** [comment]
Completely agree here @Sm0ke0ut, I have left one comment on your pull request but once that's addressed I will merge, this will half your requests @2ge.
