### ISSUE TITLE
Unable to determine configuration for Firewall/AccessRules->create

### ISSUE THREAD

**Issue by if-kyle** [jamesryanbell/cloudflare#34]
I have several calls working, but am failing to get the format correct for the create access rule found at:
https://api.cloudflare.com/#firewall-access-rule-for-a-zone-create-access-rule

https://jamesryanbell.github.io/cloudflare/source-class-Cloudflare.Zone.Firewall.AccessRules.html#59-78

I expected the following to work, based on the cloudflare API docs
```php
$firewall = new Cloudflare\Zone\Firewall\AccessRules($client);
$firewall->create('my_zone_id', 'whitelist', '{"target":"ip","value":"1.2.3.4"}', 'test from php api')
```

I however get back `Missing configuration target`.

I have tried various combinations but an unable to get this one working.

**Comment by jamesryanbell** [comment]
Hi

I'll take a look into this and let you know the outcome.

Thanks,
James

**Comment by jamesryanbell** [comment]
Hi

You need to pass the target information as an array e.g.

`$firewall->create('my_zone_id', 'whitelist', ["target"=>"ip","value"=>"1.2.3.4"], 'test from php api');`

Thanks,
James

**Comment by if-kyle** [comment]
That worked!  Thanks.  Where do you think the best place to put this might be?  I'm not super familiar with all of Cloudflare's API, is this something that should be on the main README or just the doc block for this call?
