### ISSUE TITLE
How to get results in screen?

### ISSUE THREAD

**Issue by chelssi** [jamesryanbell/cloudflare#36]
Hi,

I'm using your code but I can't get print results, How can do this? This is the code that I have:

use Cloudflare\Zone;
$client = new Cloudflare\Api('email', 'xxxxxx');
$result = new Cloudflare\Zone($client);
$result -> zones( 'domain.com', 'active', '1', '20', 'status', 'desc', 'all' );
echo $result;

nothing appears, it must present info about the zone.

Sorry for my english and than you,
Carlos

**Comment by Sm0ke0ut** [comment]
The result is a non-scalar type and can't be echoed that way. If you've error reporting enabled you would've got the following message
`Catchable fatal error: Object of class stdClass could not be converted to string`.

Please consider using `var_dump($result)`. From that point to can see/decide what information you actually need and display.

**Comment by chelssi** [comment]
Hi,

Yes, with var_dump I can already see the info that I was looking for like Zone Id.

Thank you,
Carlos
