### ISSUE TITLE
User permissions checking via organizations on non-enterprise accounts is unnecessary

### ISSUE THREAD

**Issue by chrisjohnson** [jamesryanbell/cloudflare#4]
I'm using this lib with a Pro account, and I'm getting a few errors. One such error occurs here: https://github.com/jamesryanbell/cloudflare/blob/master/src/Api.php#L129

It's trying to access ->organizations[0] despite organizations being null.

And then the bigger issue is that it's throwing an exception when attempting to use these organizations to check the permissions required to fire off the request: https://github.com/jamesryanbell/cloudflare/blob/master/src/Api.php#L154

For now, I've changed line 151 to if ( false && ... ) { to disable the permissions check and it seems to work okay, so I'm guessing it's just not necessary for Pro level accounts to perform this check. I wasn't sure how exactly you might want to approach disabling this check in the library so I figured an issue would be the best way to figure this out. For now I'm just going to fork and disable that block of code as I've done. Let me know if I can help

**Comment by tdutrion** [comment]
+1 on this issue, whereas I'm on a Free account. The same approach of commenting the check does also work as the organizations property is null.

I guess the check should be remove altogether as the [doc does not indicate any organizations key](https://www.cloudflare.com/docs/next/#user-properties) at all.

Same problem using the [organizations](https://www.cloudflare.com/docs/next/#user-s-organizations-list-organizations) api, which confirm no organizations exist on my account.

What's your take @jamesryanbell and @cloudflare ?

**Comment by jamesryanbell** [comment]
Hi

Sorry for the delay guys, I now have some spare time to work on this so I will be looking into the issue mentioned above.

Thanks,
James

**Comment by chrisjohnson** [comment]
With this issue being closed does that mean you resolved teh underlying issue? I'm still using my fork where I bypassed that bit of code entirely but would prefer to use the appropriate corrections from you if they exist
