### ISSUE TITLE
User-Agent is now required for API requests

### ISSUE THREAD

**Issue by chrisjohnson** [jamesryanbell/cloudflare#42]
As of yesterday all my API requests to CF have been blocked as being a security threat. I opened a service ticket (after waiting for their support system to come back up :-/ ) and their response was due to changes in the API, User-Agent may now be a required field. I'm not sure if this is for all users or just certain ones marked as "security threats" but I figure it can't hurt either way.

As soon as I add a User-Agent to the $headers array in Api.php, requests start working again. I'd make a PR but I haven't updated my local fork yet since I'm unsure whether my other issue has been resolved in your copy.

**Comment by jamesryanbell** [comment]
Hi, I believe this issue was resolved with the following PR: https://github.com/jamesryanbell/cloudflare/pull/41
