### ISSUE TITLE
PHP warning : curl_setopt_array() CURLOPT_FOLLOWLOCATION

### ISSUE THREAD

**Issue by Tabrisrp** [jamesryanbell/cloudflare#43]
CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set.

You might want to suppress the warning with a @ or do a workaround to prevent it on setups with open_basedir

**Comment by jamesryanbell** [comment]
Thanks for pointing this out, I have removed setting this option as it's not needed anyway.

Thanks,
James
