### ISSUE TITLE
Cloudflare errors in drupal admin

### ISSUE THREAD

**Issue by barb81** [jamesryanbell/cloudflare#44]
Hello,

I am desperate here. My Drupal admin back-end is a mess after starting cloudflare.

I followed litterally every step on Cloudflare website.

I am seriously considering stopping my paid cloudflare account. After logging in, and clicking on an item on the main menu, you seem to be logged out. If however, you add a question mark at the end of the url, and you refresh, you see the admin page again !

Even when I try to logout, it doesn't work anymore, even when the user/logout should match the exception rule I provided (user*) !

Second problem: When I add a menu item to the site, it doesn't show on the 50.000 pages. I shouldn't clear the whole Cloudflare cache after I add one menu item ??

i have read on dozens of forums that Cloudflare has left Drupal users in the cold, and now I experience the same. I would rather prefer to add a positive comment to those forums, so I want to crack this nut ! :))

Thank you in advance

**Comment by jamesryanbell** [comment]
Hi

Unfortunately I can't offer much help to be honest, I only authored this package I don't work for CloudFlare. Also I have never used the combination of Drupal and CloudFlare so I don't have the experience to help there.

I would suggest you reach out to support@cloudflare.com, I have always found their support team to be very good.

Thanks
