### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by AidasK** [jamesryanbell/cloudflare#46]
Cloudflare returns invalid json response, might be caused by network or other issues. 
https://github.com/jamesryanbell/cloudflare/blob/master/src/CloudFlare/Api.php#L237

```
ErrorException: Trying to get property of non-object
#50 vendor/jamesryanbell/cloudflare/src/CloudFlare/Api.php(238): handleError
#49 vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(36): handleError
#48 vendor/jamesryanbell/cloudflare/src/CloudFlare/Api.php(238): request
#47 vendor/jamesryanbell/cloudflare/src/CloudFlare/Api.php(141): delete
#46 vendor/jamesryanbell/cloudflare/src/CloudFlare/Zone/Cache.php(50): purge_files
#45 app/Services/CloudFlare.php(28): clearFiles
```

**Comment by AidasK** [comment]
Should be changed to:
  if (!$response || $response->success !== true) {

**Comment by Sm0ke0ut** [comment]
That change wouldn't suffice. You also need to change line https://github.com/jamesryanbell/cloudflare/blob/master/src/CloudFlare/Api.php#L238 etc. as `$response` is either `false` or `null`

**Comment by AidasK** [comment]
I think my solution is better, because it will return information such as status code, method and error message

**Comment by Sm0ke0ut** [comment]
Perhaps, but you're still trying to assign properties on a non-object. In your prefered solution you'll have to create a dummy object (\stdClass) before you can populate $response.

**Comment by AidasK** [comment]
Creating \stdClass would work perfectly.

**Comment by Vladelis** [comment]
👍

**Comment by jamesryanbell** [comment]
Thanks, sorry for the delay in getting to this! I will take a look tonight but it sounds like you guys have done the hard work already :)
