### ISSUE TITLE
PHP Fatal error:  Class 'Cloudflare\Api' not found in

### ISSUE THREAD

**Issue by qu0423** [jamesryanbell/cloudflare#47]
`<?php
use Cloudflare\Zone\Dns;
// Create a connection to the Cloudflare API which you can
// then pass into other services, e.g. DNS, later on
$client = new Cloudflare\Api('eackcfcuyv@gmail.com', 'dc88c3098d023ea0d47874698bc8cc027b1c5');
// Create a new DNS record
$dns = new Cloudflare\Zone\Dns($client);
$dns->create('www', 'A', 'name.com', '192.168.1.2', 120);
`

**according to eg, i  name above code to cf_dns.php**

but when i run " php cf_dns.php" command

**get "PHP Fatal error:  Class 'Cloudflare\Api' not found in /root/cf_dns.php on line 5"**

where is wrong?
could you help me check it?
thx

**Comment by heptagonkr** [comment]
same here

**Comment by heptagonkr** [comment]
solved 

require __DIR__ . '/vendor/autoload.php';
