### ISSUE TITLE
Integration with new Load Balancing API

### ISSUE THREAD

**Issue by Lusitaniae** [jamesryanbell/cloudflare#49]
Cloudflare just opened a limited BETA for the new Load balancing features, for now its only available through an API to accepted accounts, but it should be added to the dashboard soon.  This is the documentation they sent me.

    Setup guide: 

https://www.cloudflare.com/setup-load-balancing/ 

    REST API reference: 

https://www.cloudflare.com/docs/load-balancing-api-reference-20161220.html

**Comment by jamesryanbell** [comment]
Hi

I'm going to try and get this sorted at the weekend, thanks for flagging it up.

Thanks,
James

**Comment by jamesryanbell** [comment]
Hi

The latest release has been updated with the load balancer methods according to the official docs: https://api.cloudflare.com/

Thanks
