### ISSUE TITLE
Implement listing zones

### ISSUE THREAD

**Issue by Cysioland** [jamesryanbell/cloudflare#53]

**Comment by jamesryanbell** [comment]
Hi, can you provide some more information on this please, ideally a link to the docs. Thanks

**Comment by Cysioland** [comment]
https://api.cloudflare.com/#zone-list-zones

**Comment by jamesryanbell** [comment]
Thanks, this is already covered here: https://github.com/jamesryanbell/cloudflare/blob/master/src/CloudFlare/Zone.php#L57
