### ISSUE TITLE
Prevent use of func_get_args() in constructor

### ISSUE THREAD

**Issue by holtkamp** [jamesryanbell/cloudflare#56]
While I like the dynamic aspects of `func_get_args()` in `Api::__construct()`, it prevents proper "autowiring" by Dependency Injection Containers.

https://github.com/jamesryanbell/cloudflare/blob/003b869a814f6f3e9cd7011e97835b3b0847651d/src/CloudFlare/Api.php#L47

We use [PHP-DI](http://php-di.org/doc/autowiring.html) as Dependency Injection Container, which *would*/*should* allow us to define a dependency as:

```php
Cloudflare\Api::class => object()->constructor(get('settings.cloudFlare.credentials.email'), get('settings.cloudFlare.credentials.apiKey'))
```

However, this does not work since the autowiring process can not figure out the exact parameters  using reflection. So we have to use:

```php
\Cloudflare\Api::class => object()->constructor()
        ->method('setEmail', get('settings.cloudFlare.credentials.email'))
        ->method('setAuthKey', get('settings.cloudFlare.credentials.apiKey')),
```

Additionally, for the more specific API classes:

```php
\Cloudflare\Zone::class => object()->lazy(), //Can not be used, since the autowiring mechanism fails
```

can not be used, so we must use the more complex:

```php
\Cloudflare\Zone::class => function (ContainerInterface $container) {
    return new \Cloudflare\Zone($container->get(Cloudflare\Api::class)); 
}
```

I see two options to overcome this limitation:

- explicit use of parameters: `Api::__construct($emailAddressOrClient, $password = null)`
- introduce static 'factory' methods:
  - `Api::getInstance($email, $apiKey)`
  - `Api::getInstanceUsingExistingClient(Api $client)`

I know this is kind of an edge case, but I hope I described this "issue" properly 😄 , what do you think?

**Comment by jamesryanbell** [comment]
Thanks @holtkamp, I am currently thinking about the next major release so I will factor this in. I don't have an ETA on that release currently.

**Comment by holtkamp** [comment]
> I am currently thinking about the next major release so I will factor this in

You got a "place" to collect suggestions for such improvements? Maybe a separate 2.0-develop branche with a CHANGELOG.md with some [todo](https://github.com/blog/1825-task-lists-in-all-markdown-documents) bullets in it? Really liked your approach to an API-wrapper and suggested it plenty to other developers as inspiration and would be happy to contribute where possible 😄

**Comment by holtkamp** [comment]
>  I am currently thinking about the next major release

Before spending too much time on this, please have a look on https://blog.cloudflare.com/cloudflare-php-api-binding/
https://github.com/cloudflare/cloudflare-php
