### ISSUE TITLE
Missing API: always_use_https

### ISSUE THREAD

**Issue by shadowlmd** [jamesryanbell/cloudflare#61]
Hello.

Can you please add these API methods:

https://api.cloudflare.com/#zone-settings-get-always-use-https-setting
https://api.cloudflare.com/#zone-settings-change-always-use-https-setting

**Comment by holtkamp** [comment]
Documented in this blog post: https://blog.cloudflare.com/how-to-make-your-site-https-only/

**Comment by shadowlmd** [comment]
Can these be added as well, please?

https://api.cloudflare.com/#zone-settings-get-automatic-https-rewrites-setting
https://api.cloudflare.com/#zone-settings-change-automatic-https-rewrites-setting

**Comment by holtkamp** [comment]
@shadowlmd it is usually better to keep issues and Pull Requests isolated and small. Can you open a separate issue for this? And maybe you can try to come up with a Pull Request as well, it is not that hard, give it a try! 😄

**Comment by shadowlmd** [comment]
Sure, I just thought it was kind of easy and related, so no reason to create a separate issue. As for pull request, I have no idea what is this and where to start. Can you help? :)

**Comment by holtkamp** [comment]
You have to fork the project to your own GitHub account, then create a branch, make the changes and submit them. Then you can create a Pull Request to indicate you want YOUR changes merged in this library. 

Also Google around a bit 

https://yangsu.github.io/pull-request-tutorial/

and more detailed

https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

enjoy the ride!

**Comment by shadowlmd** [comment]
Thanks, seems like I already figured that myself. Too bad I couldn't select commits for pull request so I had to remove stuff you already created pull request for. Anyway, https://github.com/jamesryanbell/cloudflare/pull/69

**Comment by shadowlmd** [comment]
#69
