### ISSUE TITLE
Omit version information in composer.json

### ISSUE THREAD

**Issue by holtkamp** [jamesryanbell/cloudflare#66]
[Doing this is a bad practice](https://github.com/jamesryanbell/cloudflare/blob/103d4ff254a887fb1f3238480bb93fac4ebd5b2b/composer.json#L5), as documented here: https://getcomposer.org/doc/04-schema.md#version

This information will/should be derived automagically from the tags in the VCS.

**Comment by jamesryanbell** [comment]
Thanks, I'll take a look at this tonight. Also thank you for all the other work you've done on this project, much appreciated :)

Thanks,
James

**Comment by jamesryanbell** [comment]
I've updated this in the latest release

**Comment by holtkamp** [comment]
Works like charm when using a `composer update` 👍
