### ISSUE TITLE
Add zone to cloudflare

### ISSUE THREAD

**Issue by avatar** [jamesryanbell/cloudflare#81]
Hi,  i'm trying to add a zone to cloudflare, without the need for an interaction in the browser.
I successfullly added a zone, but i get stuk on step2 of the wizzard. I added the dns-records, changed the namservers, but the zone keeps at step 2 (add dns records). I already did a activation check, but this does not work.

Is this an issue with the API, or am I missing a step to actually enable the zone?

**Comment by shadowlmd** [comment]
If you post your code, there is a chance someone will help you. Anyway, here's a working example of adding a zone, managing DNS and changing some settings: https://pbin.cf/c3ed217a

**Comment by avatar** [comment]
Hi, I totally forgot i posted this question on github. 
Aparently there was something wrong with the domain. I removed it from cloudflare, and re-added it, and it worked.

Thanks for the reply.
