### ISSUE TITLE
error Cloudflare\Zone\Dns

### ISSUE THREAD

**Issue by sendyputra** [jamesryanbell/cloudflare#9]
Strict Standards: Declaration of Cloudflare\Zone\Dns::create() should be compatible with Cloudflare\Zone::create($name, Cloudflare\bool $jump_start = NULL, Cloudflare\int $organization = NULL) in /home/abcdefg/public_html/vendor/jamesryanbell/cloudflare/src/CloudFlare/Zone/Dns.php on line 102

**Comment by vesper8** [comment]
Having the same problem when trying to create an instance of $dns in order to retrieve records:
```
        $client = new Cloudflare\Api('username@gmail.com', env('CLOUDFLARE_KEY'));

        $zone = new Cloudflare\Zone($client);
        $zones = $zone->zones("mywebsite.com");

        $zoneId = $zones->result[0]->id;

        $dns = new Cloudflare\Zone\Dns($client);

        $records = $dns->list_records($zoneId);
```
        //ddd($zones);
        ddd($records);

**Comment by alekseyp** [comment]
It's only gonna work with php7 and hhvm, due to the use of 'bool' types

**Comment by vesper8** [comment]
My homestead environment is using php7 though and I'm still getting this error.

Any chance for a fix soon please?

**Comment by jamesryanbell** [comment]
Hi

Sorry about this I'll look into it tonight and hopefully have a fix for you soon.

Thanks,
James

**Comment by jamesryanbell** [comment]
Hi

The latest commit should fix this issue, any problems just let me know

Thanks
